name: Main

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Update sources
        run: python main.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated sources
          default_author: github_actions